### PR TITLE
TIme Change

### PR DESCRIPTION
**Pull request by JoshMayBalGitHub**
Change hg time pls

### CODE REVIEW

**Comment by JoshMayBalGitHub** [comment]
Also how about the new mar 21 schedule? maybe its gonna be the default one?

**Comment by JoshMayBalGitHub** [comment]
> Also how about the new mar 21 schedule? maybe its gonna be the default one?

Although i'm not sure if i want to add it since i think it isnt

**Comment by Leuqas** [comment]
> Change hg time pls

u didnt even do it properly lmao

**Comment by JoshMayBalGitHub** [comment]
@Leuqas 
Hey, i fixed it i think

**Comment by JoshMayBalGitHub** [comment]
@Leuqas 
Can ya merge it now?

**Comment by JoshMayBalGitHub** [comment]
but i am done for now i think, gonna come back to this later

**Pull request closed without merging**
